### ISSUE TITLE
Vignettes should fail gracefully when suggested packages are not available

### ISSUE THREAD

**Issue by turgeonmaxime** [sahirbhatnagar/casebase#107]
I was testing the package in a Docker container without the suggested packages, and I noticed that some of the vignettes are failing (at the very least, `smoothHazard.Rmd` does because it's missing `eha`). It would be best to change it so that it fails gracefully instead. One way to do this, for example, is to make the `eval` parameter of the relevant chunks equal to `requireNamespace("<missing-pkg>")`.

This isn't hard to do, so it would be a good first time PR

**Comment by turgeonmaxime** [comment]
The same should be true of examples that use packages from `Suggest`, they should also fail gracefully if the package in question isn't installed.

**Comment by sahirbhatnagar** [comment]
For examples, see suggestion in [r-pkgs](http://r-pkgs.had.co.nz/check.html):

>Checking for unstated dependencies in examples. If you use a package only for an example, make sure it’s listed in the `Suggests` field. Before running example code that depends on it, test to see if it’s available with `requireNamespace("pkg", quietly = TRUE)`:

```r
#' @examples
#' if (requireNamespace("dplyr", quietly = TRUE)) {
#'   ...
#' }
```

**Comment by sahirbhatnagar** [comment]
For the vignettes, it's a little more complicated to only evaluate certain chunks, because they often depend on each other. Instead, I suggest setting the global chunk option at the start of the vignette:

```r
evaluate_vignette <- requireNamespace("visreg", quietly = TRUE) & requireNamespace("splines", quietly = TRUE)
knitr::opts_chunk$set(
  collapse = TRUE, 
  eval = evaluate_vignette,
  results='hide',
  fig.show='all',
  comment = "#>"
)
```

**Comment by turgeonmaxime** [comment]
Yes, good point, I was just thinking about the same thing. I think it's fair to not build the vignette at all if the suggested packages are not installed. They're always available online anyway if a user doesn't want to install `visreg` just to look at the vignette

**Comment by turgeonmaxime** [comment]
Btw @sahirbhatnagar , there's a lot of code at the end of `vignettes/plotsmoothHazard.Rmd` that we're not running: https://github.com/sahirbhatnagar/casebase/blob/e6d8fb4d3ff92889df0034eae1687c0b9479fd8e/vignettes/plotsmoothHazard.Rmd#L389

Can we remove it? We can move this code to a separate file in the base directory that we then put in `.Rbuildignore`
