### ISSUE TITLE
`context()` is deprecated in version 3.0 of testthat 

### ISSUE THREAD

**Issue by sahirbhatnagar** [sahirbhatnagar/casebase#145]
This isn't a priority, but at some point we should update our tests to reflect that `testthat::context()` is [no longer recommended](https://testthat.r-lib.org/reference/context.html) as of [version 3.0](https://www.tidyverse.org/blog/2020/10/testthat-3-0-0/)

**Comment by turgeonmaxime** [comment]
Good catch. Not a priority, but also very easy and quick to fix.
