### ISSUE TITLE
Reformatting response in vglm

### ISSUE THREAD

**Issue by sahirbhatnagar** [sahirbhatnagar/casebase#18]
I don't think reformatting the response is necessary [here](https://github.com/sahirbhatnagar/casebase/blob/master/R/fitting.R#L95). Have you tried using the `refLevel` argument in the `multinomial` function. I found this information from [page 393 of the author's book](https://www.dropbox.com/s/0ct7n4nmarmfisb/Yee_Vector%20Generalized%20Linear%20and%20Additive%20Models.pdf?dl=0). Here is an example:

``` r
library(VGAM)
```

    ## Loading required package: stats4
    ## Loading required package: splines

``` r
pneumo <- transform(pneumo, let = log(exposure.time))

fit_ref_default <- vglm(cbind(normal, mild, severe) ~ let, multinomial, data = pneumo)
summary(fit_ref_default)
```

    ## 
    ## Call:
    ## vglm(formula = cbind(normal, mild, severe) ~ let, family = multinomial, 
    ##     data = pneumo)
    ## 
    ## Pearson residuals:
    ##                        Min      1Q   Median     3Q    Max
    ## log(mu[,1]/mu[,3]) -0.7547 -0.2003 -0.04325 0.4364 0.9228
    ## log(mu[,2]/mu[,3]) -0.8138 -0.4382 -0.12128 0.1572 1.0323
    ## 
    ## Coefficients:
    ##               Estimate Std. Error z value Pr(>|z|)    
    ## (Intercept):1  11.9751     2.0004   5.986 2.15e-09 ***
    ## (Intercept):2   3.0391     2.3761   1.279    0.201    
    ## let:1          -3.0675     0.5652  -5.427 5.73e-08 ***
    ## let:2          -0.9021     0.6690  -1.348    0.178    
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Number of linear predictors:  2 
    ## 
    ## Names of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3])
    ## 
    ## Dispersion Parameter for multinomial family:   1
    ## 
    ## Residual deviance: 5.3474 on 12 degrees of freedom
    ## 
    ## Log-likelihood: -25.2505 on 12 degrees of freedom
    ## 
    ## Number of iterations: 4

``` r
fit_ref_normal <- vglm(cbind(normal, mild, severe) ~ let, multinomial(refLevel = 1), data = pneumo)
summary(fit_ref_normal)
```

    ## 
    ## Call:
    ## vglm(formula = cbind(normal, mild, severe) ~ let, family = multinomial(refLevel = 1), 
    ##     data = pneumo)
    ## 
    ## Pearson residuals:
    ##                        Min      1Q  Median      3Q    Max
    ## log(mu[,2]/mu[,1]) -0.7614 -0.4106 -0.3104 0.03253 1.2672
    ## log(mu[,3]/mu[,1]) -0.8328 -0.2867 -0.0419 0.19742 0.8999
    ## 
    ## Coefficients:
    ##               Estimate Std. Error z value Pr(>|z|)    
    ## (Intercept):1  -8.9360     1.5804  -5.654 1.57e-08 ***
    ## (Intercept):2 -11.9751     2.0004  -5.986 2.15e-09 ***
    ## let:1           2.1654     0.4575   4.733 2.21e-06 ***
    ## let:2           3.0675     0.5652   5.427 5.73e-08 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Number of linear predictors:  2 
    ## 
    ## Names of linear predictors: log(mu[,2]/mu[,1]), log(mu[,3]/mu[,1])
    ## 
    ## Dispersion Parameter for multinomial family:   1
    ## 
    ## Residual deviance: 5.3474 on 12 degrees of freedom
    ## 
    ## Log-likelihood: -25.2505 on 12 degrees of freedom
    ## 
    ## Number of iterations: 4

**Comment by turgeonmaxime** [comment]
Fixed #20
