### ISSUE TITLE
Formulas 

### ISSUE THREAD

**Issue by Jesse-Islam** [sahirbhatnagar/casebase#60]
Currently, It seems we can't use any formula notations ( . - ) in the formula portion of fitSmoothHazard. Just creating the formula externally for now to bypass that.

`model4 <- fitSmoothHazard(DeadOfPrCa ~ Follow.Up.Time + ScrArm, data = ERSPC, time='Follow.Up.Time',  ratio = 100)` ok
`model4 <- fitSmoothHazard(DeadOfPrCa ~ ., data = ERSPC, time='Follow.Up.Time',  ratio = 100)` not ok

**Comment by turgeonmaxime** [comment]
Thanks @Jesse-Islam for reporting this. Just to make sure we have the same error message, this is what I get:

``` r
library(casebase)
#> See example usage at http://sahirbhatnagar.com/casebase/
model4 <- fitSmoothHazard(DeadOfPrCa ~ ., data = ERSPC, time='Follow.Up.Time', ratio = 100)
#> Error in terms.formula(tmp, simplify = TRUE): '.' in formula and no 'data' argument
```

<sup>Created on 2019-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If this what you get too?

**Comment by Jesse-Islam** [comment]
Yep exactly that.

Best,
Jesse

**Comment by turgeonmaxime** [comment]
I see what the problem is. When we update the formula to add the offset, the dot cannot be expanded because it doesn't have access to the data. So the solution is expanded the dot first. I have pull-request coming soon that will fix the issue :+1:
