### ISSUE TITLE
predict.cv.glmnet no longer exported in version 3.0 of glmnet package

### ISSUE THREAD

**Issue by sahirbhatnagar** [sahirbhatnagar/casebase#72]
In the most [recent update to glmnet](https://cran.r-project.org/web/packages/glmnet/news/news.html) `predict.cv.glmnet` is no longer exported. This raises a NOTE in the checks because of [this line](https://github.com/sahirbhatnagar/casebase/blob/master/R/absoluteRisk-cr.R#L188). Do we need this for the moment? I recall that competing risk with glmnet wasn't fully tested.

**Comment by turgeonmaxime** [comment]
Good catch. There should be another way of doing this using `NextMethod`, that would not involve calling `predict.cv.glmnet` directly. But I'm not sure how that function works.

On the other hand, you're right that competing risks with glmnet wasn't fully tested. I've never really figured out how to get around the problem with offsets being dropped. So I think we should give the appropriate error messages in case a user tries to do regularized competing risks and move this to a future release.
